Bac 30 store credit payments for bill
Creationals/BacchUX pull request #47
Opened 2020-10-06 10:51 UTC by PotatoesFall

2020-10-06 14:03 UTC, ViNguyen91 reviewed
Heel mooi gedaan Martin. The interface is clear and easy to use.

However, when I click the credit payment, it takes a while to go back to the order page. And if I "accidentally" click more than 1 times the Credit payment button, it will charge the customer more than 1 time.

2020-10-08 07:37 UTC, filiusalwin requested changes
New lay out looks nice. Credit payment works.
- Direct Payment has no confirmation. If you accidentally press that button the payment is immediately done and the bill is gone. A confirmation as with creditpayment is needed, I think.

2020-10-08 07:37 UTC, filiusalwin commented on src/main/java/nl/miwgroningen/se/ch3/bacchux/model/CreditPayment.java
> +    public CreditPayment(User user, Integer amount, boolean paid, String orderJson) {
Why are there constrtuctors here? Not needed with spring boot, I suppose?

2020-10-08 07:49 UTC, PotatoesFall commented on src/main/java/nl/miwgroningen/se/ch3/bacchux/model/CreditPayment.java
> +    public CreditPayment(User user, Integer amount, boolean paid, String orderJson) {
When there are no constructors, spring uses the default no-args constructor. Since I specified a constructor for ease of use, I also needed to specify the no-args constructor for spring, since it otherwise doesn't have the default constructor.

2020-10-08 08:04 UTC, merged